vektorprogrammet/homepage

- .github/workflows/node.js.yml
Github action will check that building the project works.
> Add nodejs build CI

- src/App.tsx
- src/pages/public/Assistenter/components/Assistenter.tsx
- src/pages/public/Assistenter/index.ts
- src/pages/public/ForForeldre/components/ForForeldre.tsx
- src/pages/public/ForForeldre/index.ts
- src/pages/public/ForSkoler/components/ForSkoler.tsx
- src/pages/public/ForSkoler/index.ts
- src/pages/public/Kontakt/components/Kontakt.tsx
- src/pages/public/Kontakt/index.ts
- src/pages/public/OmOss/components/OmOss.tsx
- src/pages/public/OmOss/index.ts
- src/pages/public/Team/components/Team.tsx
- src/pages/public/Team/index.ts
- src/pages/public/routes.ts
Adding routing system with pges in subfolders.
> VF-3: Skeleton public pages

- public/index.html
The info and color scheme was stolen from the current frontend
> [NOJIRA] chore: remove comments and add opengraph info to index.html

- .github/workflows/node.js.yml
Change from master to main in workflow
> Update node.js workflow branch

- src/components/Pages/TextPictureCard.tsx
- src/pages/public/ForSkoler/components/BorderContentCard.tsx
- src/pages/public/OmOss/components/Accordion.tsx
- src/pages/public/OmOss/components/OmOss.tsx
Adds om oss page 
And accordions
> [VF-35] feature: om oss page

- src/pages/public/StagingServerOverview/components/FetchUtils.ts
- src/pages/public/StagingServerOverview/components/ServerOverview.tsx
- src/pages/public/StagingServerOverview/index.ts
- src/pages/public/routes.ts
Add snippet below to `routes.ts` for reviewing.
```
import ServerOverview from "./StagingServerOverview";
.
.
.
{ route: "/staging", component: ServerOverview },
```
> [VF-38] Staging server overview

- .github/pull_request_template.md
Adds PR-template, which prefills the body of a PR when creating it.
> VF-66 Create pull_request_template.md

- tailwind.config.js
Adds a DaisyUI color theme that allows for customizing colors of DaisyUI components.
VF-61
> [VF-61] Add DaisyUI theme

- src/pages/public/Assistenter/components/CityCard/CityButton.tsx
> Removed Oslo from form.

- src/components/Pages/TextPictureCard.tsx
- src/pages/public/Assistenter/components/Assistenter.tsx
- src/pages/public/Assistenter/components/AssistenterCard.tsx
- src/pages/public/ForForeldre/components/ForForeldre.tsx
- src/pages/public/ForSkoler/components/BorderContentCard.tsx
- src/pages/public/ForSkoler/components/ForSkoler.tsx
- src/pages/public/ForSkoler/components/PageSection.tsx
- src/pages/public/ForSkoler/components/PageTitleCard.tsx
- src/pages/public/Kontakt/components/Kontakt.tsx
- src/pages/public/Kontakt/components/KontaktCard.tsx
- src/pages/public/OmOss/components/Accordion.tsx
- src/pages/public/OmOss/components/OmOss.tsx
- src/pages/public/Team/components/Division.tsx
- src/pages/public/Team/components/Team.tsx
- src/pages/public/Team/components/TeamCard.tsx
- src/pages/public/Team/components/TeamTabs.tsx
> VF 62 fix dark mode in all pages

- src/api/Sponsor.ts
Changed links to working links. Check if these are really still our "samarbeidspartnere".
VF-80
> vf-80-fix-links-in-footer

- src/pages/public/Team/components/TeamCard.tsx
- src/pages/public/Team/components/TeamTabs.tsx
> Made the tabs and picture responsive

- .eslintrc.js
- src/pages/public/Kontakt/components/Division.tsx
- src/pages/public/Kontakt/components/Kontakt.tsx
- src/pages/public/Kontakt/components/KontaktCard.tsx
- src/pages/public/Kontakt/components/KontaktOss.tsx
Oppdaterte VF-55 for å være kompatibel med main. 
VF-55
> Oppdaterte VF-55 med main.

- src/App.tsx
- src/components/Header/UserAvatar.tsx
- src/pages/public/Kontrollpanel/components/Kontrollpanel.tsx
- src/pages/public/routes.ts
Add control panel component and folder to pages, change routing to connect control panel to page routing
VF-84
> Control panel page, control panel routing

- src/pages/controlpanel/components/InfoBoks.tsx
- src/pages/controlpanel/index.tsx
Made infobox component for controlpanel to be used on every page
VF-120
> Vf 120 lag kontrollpanel komponent for info

- src/pages/public/index.tsx
> La til ScrollRestoration komponent

- src/pages/public/Team/TeamPages/Hovedstyret/Hovedstyret.tsx
- src/pages/public/Team/TeamPages/routes.tsx
- src/pages/public/Team/components/TeamTabs.tsx
Lagde en side for hovedstyret under teams. Linket knappen på teamssiden til å gå til hovedstyretsiden.
VF-118
> Vf 118 lag hovedstyret side

- src/components/Header/UserAvatar.tsx
Updated the user avatar dropdown menu link names to:
- Kontrollpanel
- Profil
- Mine søknader
- Mine utlegg 
- Logg ut
VF-92
> Update dropdown menu link names

- src/pages/public/Team/TeamPages/Bergen/Rekruttering.tsx
- src/pages/public/Team/TeamPages/Bergen/Skolekoordinering.tsx
- src/pages/public/Team/TeamPages/Bergen/Styret.tsx
- src/pages/public/Team/TeamPages/TeamTemplate.tsx
- src/pages/public/Team/TeamPages/index.ts
- src/pages/public/Team/TeamPages/routes.tsx
Lag sider til hvert av teamene i bergen. Fiks unique key i TeamTemplate.tsx. 
VF-88
> Vf 88 lag bergen team pages

- src/pages/controlpanel/components/Teaminteresse.tsx
- src/pages/controlpanel/routes.tsx
Made teaminterest page in control panel. Different page for each team with hardcoded user data
VF-115
> VF-115 teaminteresse side ferdig

- src/pages/controlpanel/components/Navbar.tsx
- src/pages/controlpanel/components/Skoler.tsx
- src/pages/controlpanel/components/Teaminteresse.tsx
Create a navBar component and implement navbar into skoler.tsx and Teaminteresse.tsx
VF-126
> Vf 126 gjor kontrollpanel navbar til en universal komponent

- src/pages/controlpanel/components/Teammedlemmer.tsx
- src/pages/controlpanel/routes.tsx
Make teammedlemmer page
VF-109
> Vf 109 lag teammedlemmer side

- src/pages/public/Kontakt/components/KontaktOss.tsx
- src/pages/public/Team/components/TeamTabs.tsx
- src/pages/public/routes.tsx
> Added session storage

- src/App.tsx
- src/components/AppFooter/AppFooter.tsx
- src/components/Header/AppHeader.tsx
- src/components/Header/UserAvatar.tsx
- src/pages/public/Profil/components/Profil.tsx
- src/pages/public/Profil/index.ts
- src/pages/public/routes.tsx
> Vf 91 lag profilside

- package.json
- src/App.tsx
- src/components/Header/UserAvatar.tsx
- src/pages/public/User/Utlegg.tsx
- src/pages/public/routes.tsx
- tailwind.config.js
- yarn.lock
> VF-94 lag nytt utlegg skjema

- src/pages/controlpanel/components/SideBar.tsx
- src/pages/controlpanel/index.tsx
Removed "fixed" from SideBar and added minimum width
VF-129
> fix: :bug: fix SideBar layout styling

- src/pages/controlpanel/components/Team.tsx
- src/pages/controlpanel/components/Team/Team.tsx
- src/pages/controlpanel/components/Team/Teammedlemmer.tsx
- src/pages/controlpanel/routes.tsx
Add teams table to control panel
VF-113
> VF-113 Create teams table in controlpanel

- package.json
- pnpm-lock.yaml
This reverts commit fa124671d72ad52ac50a9bf46176ed0a419d9905.
> Revert "fix(deps): update dependency web-vitals to v4 (#306)"

- package.json
- pnpm-lock.yaml
- src/reportWebVitals.ts
Replace "ReportHandler" with (metric: MetricType) => void. 
Replace "getXXX" functions with "onXXX".
> Upgrade web vitals to v4

- src/components/Header/AppHeader.tsx
- src/components/Header/LoginButtons.tsx
- src/components/Header/Tab.tsx
Create a new header with tabs, that takes up less space
VF-177
> Vf 177 add tabs to header

- src/components/Header/AppHeader.tsx
- src/components/Header/LoginButtons.tsx
- src/components/Header/MobileMenu.tsx
- src/pages/controlpanel/components/LoginPopup.tsx
- src/pages/controlpanel/index.tsx
Deleger profilhåndtering til kontrollpanelet istedenfor hjemmesiden
VF-169
> Vf 169 flytt logg inn til kontrollpanel

- biome.json
- package.json
- remove deprecated trailingComma option
- only warn on noSvgWithoutTitle
- only lint & format files tracked by git
- deprecate --apply for --write
VF-XXX
> Update Biome configuration

- src/routes/_home.skoler.tsx
- src/routes/_home.tsx
> hide the navbar for large screens on the small screens
